#!/usr/bin/ruby

#use_git_submodules true

# tpope
bundle 'vim-eunuch', :git => 'git://github.com/tpope/vim-eunuch.git'
bundle 'fugitive',   :git => 'git://github.com/tpope/vim-fugitive.git'
bundle 'unimpaired', :git => 'git://github.com/tpope/vim-unimpaired.git'
bundle 'afterimage', :git => 'git://github.com/tpope/vim-afterimage.git'
bundle 'abolish',    :git => 'git://github.com/tpope/vim-abolish.git'
bundle 'git',        :git => 'git://github.com/tpope/vim-git.git'
bundle 'rake',       :git => 'git://github.com/tpope/vim-rake.git'
bundle 'markdown',   :git => 'git://github.com/tpope/vim-markdown.git'
bundle 'commentary', :git => 'git://github.com/tpope/vim-commentary.git'
bundle 'rails',      :git => 'git://github.com/tpope/vim-rails.git'
bundle 'repeat',     :git => 'git://github.com/tpope/vim-repeat.git'
bundle 'surround',   :git => 'git://github.com/tpope/vim-surround.git'
bundle 'endwise',    :git => 'git://github.com/tpope/vim-endwise'
bundle 'ragtag',     :git => 'git://github.com/tpope/vim-ragtag'
bundle 'bundler',    :git => 'git://github.com/tpope/vim-bundler.git'
bundle 'cucumber',   :git => 'git://github.com/tpope/vim-cucumber.git'

bundle 'ctrlp',             :git => 'git://github.com/kien/ctrlp.vim.git'
bundle 'buffergator',       :git => 'git://github.com/jeetsukumaran/vim-buffergator'
bundle 'supertab',          :git => 'git://github.com/ervandew/supertab.git'
bundle 'ruby',              :git => 'git://github.com/vim-ruby/vim-ruby.git'
bundle 'javascript',        :git => 'git://github.com/pangloss/vim-javascript'
bundle 'syntastic',         :git => 'git://github.com/scrooloose/syntastic'
bundle 'rdoc',              :git => 'git://github.com/depuracao/vim-rdoc'
bundle 'vroom',             :git => 'git://github.com/skalnik/vim-vroom.git'
bundle 'ack',               :git => 'git://github.com/mileszs/ack.vim'
bundle 'tabular',           :git => 'git://github.com/godlygeek/tabular.git'
bundle 'bufkill',           :git => 'git://github.com/hced/bufkill-vim.git'
bundle 'textobj-user',      :git => 'git://github.com/kana/vim-textobj-user.git'
bundle 'textobj-rubyblock', :git => 'git://github.com/nelstrom/vim-textobj-rubyblock'
bundle 'scss-syntax',       :git => 'git://github.com/cakebaker/scss-syntax.vim.git'
bundle 'html5',             :git => 'git://github.com/othree/html5.vim.git'

bundle 'phpcomplete',      :git => 'git://github.com/shawncplus/phpcomplete.vim'
bundle 'snipmate',         :git => 'git://github.com/msanders/snipmate.vim.git'
bundle 'ruby-refactoring', :git => 'git://github.com/ecomba/vim-ruby-refactoring.git'
bundle 'coffee-script',    :git => 'git://github.com/kchmck/vim-coffee-script'
bundle 'handlebars',       :git => 'git://github.com/nono/vim-handlebars.git'
bundle 'wiki',             :git => 'git://github.com/vim-scripts/vimwiki.git'
bundle 'cvim',             :git => 'git://github.com/vim-scripts/c.vim.git'

# colours
bundle 'inkpot',     :git => 'git://github.com/ciaranm/inkpot'
bundle 'vividchalk', :git => 'git://github.com/tpope/vim-vividchalk.git'
bundle 'peaksea',    :git => 'git://github.com/vim-scripts/peaksea.git'
bundle 'solarized',  :git => 'git://github.com/altercation/vim-colors-solarized'

# maybe use in the future
# bundle 'bufexplorer',       :git => 'git://github.com/slack/vim-bufexplorer.git'
#bundle 'jquery', :git => 'git://github.com/vim-scripts/jQuery'
#bundle 'gnupg', :git => 'git://github.com/vim-scripts/gnupg.vim.git'
#bundle 'tslime', :git => 'git://github.com/jgdavey/tslime.vim.git'
#bundle 'vim-turbux', :git => 'git://github.com/jgdavey/vim-turbux.git'
#bundle 'slimv', :git => 'git://github.com/vim-scripts/slimv.vim.git'
#bundle 'delimitmate', :git =>'git://github.com/Raimondi/delimitMate.git'
#bundle 'align', :git=> 'git://github.com/tsaleh/vim-align.git'
#bundle 'shoulda', :git => 'git://github.com/tsaleh/vim-shoulda.git'
#bundle 'tcomment', :git => 'git://github.com/tsaleh/vim-tcomment.git'
#bundle 'camel-case-motion', :git => 'git://github.com/bkad/CamelCaseMotion'
#bundle 'indexed-search', :vim_script_id => 7062
#bundle 'json', :vim_script_id => 10853
#bundle 'lusty-juggler', :git => 'git://github.com/sjbach/lusty'
#bundle 'csscolor', :git => 'git://github.com/vim-scripts/css_color.vim.git'
#git://github.com/majutsushi/tagbar.git
#Bundle 'lokaltog/vim-easymotion'
#Bundle 'rstacruz/sparkup', {'rtp': 'vim/'}
#Bundle 'dchelimsky/sweet-rspec-vim'
#" Colour schemes
#"get_repo "guns" "xoria256.vim"
#"get_repo "wgibbs" "vim-irblack"
#"cschlueter" "vim-mustang"
#"get_repo "andyferra" "molokai"
#" possible future bundles
#"mhz" "vim-matchit"
#"astashov" "vim-ruby-debugger"
#"jc00ke" "taglist.vim"
#"chrismetcalf" "vim-yankring"
#"chrismetcalf" "vim-rainbow"
#"michaeljsmith" "vim-indent-object"
#"chrisbra" "csv.vim"
#"ZeusTheTrueGod" "vim-format-js"
#"int3" "vim-extradite"
#"sjl" "gundo.vim"#
