#!/usr/bin/env ruby

class ProjectCompletion
  def initialize(command)
    @command = command
  end

  def matches
    projects.select do |task|
      task[0, typed.length] == typed
    end
  end

  def typed
    @command[/\s(.+?)$/, 1] || ''
  end

  def projects
    `ls ~/projects/`.split.map{|p| '~/projects/'+p } + `ls ~/myprojects/`.split.map{|p| '~/myprojects/'+p }
  end
end

puts ProjectCompletion.new(ENV["COMP_LINE"]).matches
exit 0

