filetype plugin indent on
set nocompatible
set modelines=1
set foldlevelstart=99
set wildmode=list:longest
set history=10000
set undolevels=10000
set cpoptions+=$
set number
set hlsearch
set ignorecase
set cursorline
set nobackup
set noswapfile
set nowb
set hidden
set tabstop=2
set expandtab
set shiftwidth=2
set softtabstop=2
set shiftround
set undofile
set undodir=~/.vim/undo
set tags+=gems.tags
set background=dark
set nowrap
set textwidth=0
set colorcolumn=80
